# Use Nginx base image
FROM nginx:alpine

# Copy your HTML file into Nginx web root
COPY app/index.html /usr/share/nginx/html/index.html

# Expose port
EXPOSE 80

# Run nginx
CMD ["nginx", "-g", "daemon off;"]

